name: $(TeamProject)_$(Build.DefinitionName)_$(date:yyyyMMdd)$(Hours)_$(rev:.r)
trigger:
- main
- qa
variables:
  - name: isMainBranch
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: isQABranch
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/qa')]
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - group: AZURE_PORTAL_PROD_LIBRARY_AI
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/qa') }}:
    - group: AZURE_PORTAL_QA_LIBRARY_AI
  - name: BUILD_TAG
    value: $(Build.BuildId)
 
pool:
  vmImage: ubuntu-latest
 
resources:
  repositories:
    - repository: PipelineRepository
      type: git
      name: your-org/common-pipeline-template-python
      ref: refs/heads/multiPoolDeploy
 
stages:
  - stage: DeployQA
    displayName: DeployQA
    condition: and(eq(variables.isQABranch, true), eq(variables.isMainBranch, false))
    jobs:
      - template: 00_pipeline.yml@PipelineRepository
        parameters:
          deployName: "IMAGE_TOOLS_QA"
          environment: qa
          displayName: "Deploy QA"
          agentPoolName: 'Azure Pipelines'
          dockerVersion: $(DOCKER_VERSION)
          crServiceConnection: $(CONTAINER_REGISTRY_CONNECTION)
          aksImageName: $(AKS_IMAGE_TOOLS_IMAGE_NAME)
          fileAksReplaceTokenPath: "$(System.DefaultWorkingDirectory)/aks.yml"
          aksServiceConnection: $(AKS_SERVICE_CONNECTION)
          aksNamespace: $(AKS_NAMESPACE)
          aksYmlPath: "$(System.DefaultWorkingDirectory)/aks.yml"
  - stage: DeployProduction
    displayName: DeployProduction
    condition: and(eq(variables.isMainBranch, true), eq(variables.isQABranch, false))
    jobs:
      - template: 00_pipeline.yml@PipelineRepository
        parameters:
          deployName: "IMAGE_TOOLS_PRODUCTION"
          environment: prod
          displayName: "Deploy Productivo"
          agentPoolName: 'Azure Pipelines'
          dockerVersion: $(DOCKER_VERSION)
          crServiceConnection: $(CONTAINER_REGISTRY_CONNECTION)
          aksImageName: $(AKS_IMAGE_TOOLS_IMAGE_NAME)
          fileAksReplaceTokenPath: "$(System.DefaultWorkingDirectory)/aks.yml"
          aksServiceConnection: $(AKS_SERVICE_CONNECTION)
          aksNamespace: $(AKS_NAMESPACE)
          aksYmlPath: "$(System.DefaultWorkingDirectory)/aks.yml"