apiVersion: v1
kind: ConfigMap
metadata:
  name: image-tools-configmap
  namespace: default
data:
  IMAGE_TOOLS_API_GLOBAL_PREFIX: "/api/v1"
  IMAGE_TOOLS_API_TOKENS: "your-api-token-here"
  MAX_UPLOAD_MB: "10"
  IMAGE_PROCESS_VALIDATE_HTTPS_URL: "true"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
