apiVersion: v1
kind: Secret
metadata:
  name: image-tools-configmap-secret
  namespace: default
type: Opaque
stringData:
  # No se requieren secretos para el endpoint image-process
  # Este archivo se mantiene como placeholder para futuras necesidades
